// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurvey.proto

package grpc.examples.smartsurvey;

public interface loginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartsurvey.loginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
