// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurveymon.proto

package grpc.examples.smartsurvey;

public interface monitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartsurvey.monitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 movement = 1;</code>
   */
  int getMovement();

  /**
   * <code>int32 images = 2;</code>
   */
  int getImages();

  /**
   * <code>string voices = 3;</code>
   */
  java.lang.String getVoices();
  /**
   * <code>string voices = 3;</code>
   */
  com.google.protobuf.ByteString
      getVoicesBytes();
}
