// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurveyrep.proto

package grpc.examples.smartsurvey;

/**
 * <pre>
 *the request message containing motion and noise level
 * </pre>
 *
 * Protobuf type {@code smartsurvey.reportRequest}
 */
public  final class reportRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartsurvey.reportRequest)
    reportRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use reportRequest.newBuilder() to construct.
  private reportRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private reportRequest() {
    motion_ = "";
    noise_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private reportRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            motion_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            noise_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.examples.smartsurvey.SmartSurveyRepServiceImpl.internal_static_smartsurvey_reportRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.examples.smartsurvey.SmartSurveyRepServiceImpl.internal_static_smartsurvey_reportRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.examples.smartsurvey.reportRequest.class, grpc.examples.smartsurvey.reportRequest.Builder.class);
  }

  public static final int MOTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object motion_;
  /**
   * <code>string motion = 1;</code>
   */
  public java.lang.String getMotion() {
    java.lang.Object ref = motion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      motion_ = s;
      return s;
    }
  }
  /**
   * <code>string motion = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMotionBytes() {
    java.lang.Object ref = motion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      motion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOISE_FIELD_NUMBER = 3;
  private volatile java.lang.Object noise_;
  /**
   * <code>string noise = 3;</code>
   */
  public java.lang.String getNoise() {
    java.lang.Object ref = noise_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      noise_ = s;
      return s;
    }
  }
  /**
   * <code>string noise = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNoiseBytes() {
    java.lang.Object ref = noise_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      noise_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMotionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, motion_);
    }
    if (!getNoiseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, noise_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMotionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, motion_);
    }
    if (!getNoiseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, noise_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.examples.smartsurvey.reportRequest)) {
      return super.equals(obj);
    }
    grpc.examples.smartsurvey.reportRequest other = (grpc.examples.smartsurvey.reportRequest) obj;

    boolean result = true;
    result = result && getMotion()
        .equals(other.getMotion());
    result = result && getNoise()
        .equals(other.getNoise());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOTION_FIELD_NUMBER;
    hash = (53 * hash) + getMotion().hashCode();
    hash = (37 * hash) + NOISE_FIELD_NUMBER;
    hash = (53 * hash) + getNoise().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.examples.smartsurvey.reportRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.examples.smartsurvey.reportRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.examples.smartsurvey.reportRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.examples.smartsurvey.reportRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *the request message containing motion and noise level
   * </pre>
   *
   * Protobuf type {@code smartsurvey.reportRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartsurvey.reportRequest)
      grpc.examples.smartsurvey.reportRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.examples.smartsurvey.SmartSurveyRepServiceImpl.internal_static_smartsurvey_reportRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.examples.smartsurvey.SmartSurveyRepServiceImpl.internal_static_smartsurvey_reportRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.examples.smartsurvey.reportRequest.class, grpc.examples.smartsurvey.reportRequest.Builder.class);
    }

    // Construct using grpc.examples.smartsurvey.reportRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      motion_ = "";

      noise_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.examples.smartsurvey.SmartSurveyRepServiceImpl.internal_static_smartsurvey_reportRequest_descriptor;
    }

    @java.lang.Override
    public grpc.examples.smartsurvey.reportRequest getDefaultInstanceForType() {
      return grpc.examples.smartsurvey.reportRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.examples.smartsurvey.reportRequest build() {
      grpc.examples.smartsurvey.reportRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.examples.smartsurvey.reportRequest buildPartial() {
      grpc.examples.smartsurvey.reportRequest result = new grpc.examples.smartsurvey.reportRequest(this);
      result.motion_ = motion_;
      result.noise_ = noise_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.examples.smartsurvey.reportRequest) {
        return mergeFrom((grpc.examples.smartsurvey.reportRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.examples.smartsurvey.reportRequest other) {
      if (other == grpc.examples.smartsurvey.reportRequest.getDefaultInstance()) return this;
      if (!other.getMotion().isEmpty()) {
        motion_ = other.motion_;
        onChanged();
      }
      if (!other.getNoise().isEmpty()) {
        noise_ = other.noise_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.examples.smartsurvey.reportRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.examples.smartsurvey.reportRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object motion_ = "";
    /**
     * <code>string motion = 1;</code>
     */
    public java.lang.String getMotion() {
      java.lang.Object ref = motion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        motion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string motion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMotionBytes() {
      java.lang.Object ref = motion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        motion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string motion = 1;</code>
     */
    public Builder setMotion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      motion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string motion = 1;</code>
     */
    public Builder clearMotion() {
      
      motion_ = getDefaultInstance().getMotion();
      onChanged();
      return this;
    }
    /**
     * <code>string motion = 1;</code>
     */
    public Builder setMotionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      motion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object noise_ = "";
    /**
     * <code>string noise = 3;</code>
     */
    public java.lang.String getNoise() {
      java.lang.Object ref = noise_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        noise_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string noise = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNoiseBytes() {
      java.lang.Object ref = noise_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        noise_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string noise = 3;</code>
     */
    public Builder setNoise(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      noise_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string noise = 3;</code>
     */
    public Builder clearNoise() {
      
      noise_ = getDefaultInstance().getNoise();
      onChanged();
      return this;
    }
    /**
     * <code>string noise = 3;</code>
     */
    public Builder setNoiseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      noise_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartsurvey.reportRequest)
  }

  // @@protoc_insertion_point(class_scope:smartsurvey.reportRequest)
  private static final grpc.examples.smartsurvey.reportRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.examples.smartsurvey.reportRequest();
  }

  public static grpc.examples.smartsurvey.reportRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<reportRequest>
      PARSER = new com.google.protobuf.AbstractParser<reportRequest>() {
    @java.lang.Override
    public reportRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new reportRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<reportRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<reportRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.examples.smartsurvey.reportRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

