// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurveyrep.proto

package grpc.examples.smartsurvey;

public interface reportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartsurvey.reportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string motion = 1;</code>
   */
  java.lang.String getMotion();
  /**
   * <code>string motion = 1;</code>
   */
  com.google.protobuf.ByteString
      getMotionBytes();

  /**
   * <code>string noise = 3;</code>
   */
  java.lang.String getNoise();
  /**
   * <code>string noise = 3;</code>
   */
  com.google.protobuf.ByteString
      getNoiseBytes();
}
