// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurveyrep.proto

package grpc.examples.smartsurvey;

public interface reportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartsurvey.reportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string notice = 1;</code>
   */
  java.lang.String getNotice();
  /**
   * <code>string notice = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoticeBytes();
}
