// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurveymon.proto

package grpc.examples.smartsurvey;

public final class SmartSurveyMonServiceImpl {
  private SmartSurveyMonServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartsurvey_monitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartsurvey_monitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartsurvey_monitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartsurvey_monitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024smartsurveymon.proto\022\013smartsurvey\"B\n\016m" +
      "onitorRequest\022\020\n\010movement\030\001 \001(\005\022\016\n\006image" +
      "s\030\002 \001(\005\022\016\n\006voices\030\003 \001(\t\"\036\n\017monitorRespon" +
      "se\022\013\n\003val\030\001 \001(\t2V\n\007Monitor\022K\n\010activity\022\033" +
      ".smartsurvey.monitorRequest\032\034.smartsurve" +
      "y.monitorResponse\"\000(\0010\001B8\n\031grpc.examples" +
      ".smartsurveyB\031SmartSurveyMonServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartsurvey_monitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartsurvey_monitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartsurvey_monitorRequest_descriptor,
        new java.lang.String[] { "Movement", "Images", "Voices", });
    internal_static_smartsurvey_monitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartsurvey_monitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartsurvey_monitorResponse_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
