// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurvey.proto

package grpc.examples.smartsurvey;

public final class SmartSurveyServiceImpl {
  private SmartSurveyServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartsurvey_loginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartsurvey_loginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartsurvey_loginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartsurvey_loginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021smartsurvey.proto\022\013smartsurvey\"\034\n\014logi" +
      "nRequest\022\014\n\004name\030\001 \001(\t\" \n\rloginResponse\022" +
      "\017\n\007message\030\001 \001(\t2\216\001\n\007Checkin\022@\n\005login\022\031." +
      "smartsurvey.loginRequest\032\032.smartsurvey.l" +
      "oginResponse\"\000\022A\n\006logout\022\031.smartsurvey.l" +
      "oginRequest\032\032.smartsurvey.loginResponse\"" +
      "\000B5\n\031grpc.examples.smartsurveyB\026SmartSur" +
      "veyServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartsurvey_loginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartsurvey_loginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartsurvey_loginRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_smartsurvey_loginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartsurvey_loginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartsurvey_loginResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
