// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartsurvey.proto

package grpc.examples.smartsurvey;

public interface loginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartsurvey.loginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
